[package]
name = "binary_search_lib"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "binary_search_lib"
crate-type = ["cdylib"]  # Dynamically linked library

[profile.release]
debug = true
